//! Durable execution intent for tool-runtime tasks.
//!
//! This module implements the Phase 5.2 requirement that side-effecting or
//! resumable tools **must** persist a durable execution intent record
//! **before** the tool callback runs. If persistence fails, the tool
//! execution is blocked (fail-closed).
//!
//! # Operation identity
//!
//! A raw `tool_call_id` is generated by the LLM provider and is unique
//! *within a single response*. It does not survive task retries — a
//! retried child task that re-reads the parent's continuation will see
//! the same `tool_call_id`, but from the server's perspective it is a
//! new attempt. [`OperationId`] combines the **child task id** (stable
//! across retries for the same logical unit of work) with the raw
//! `tool_call_id` to form a server-generated identity that:
//!
//! - Is unique across the entire system (UUID-backed task id).
//! - Survives retries and restarts.
//! - Distinguishes independent tool calls that happen to share the
//!   same LLM-assigned call id.
//!
//! # Tool effect classification
//!
//! [`ToolEffectClass`] classifies every tool call into one of three
//! categories that control the durability and retry rules:
//!
//! | Class | Intent required? | Retry rule |
//! |-------|-----------------|------------|
//! | [`ReplaySafe`](ToolEffectClass::ReplaySafe) | No | Re-execute freely; result is deterministic. |
//! | [`SideEffecting`](ToolEffectClass::SideEffecting) | **Yes** | Fail-closed if intent not persisted; no automatic retry once started. |
//! | [`Resumable`](ToolEffectClass::Resumable) | **Yes** | Fail-closed if intent not persisted; may resume an in-progress operation. |
//!
//! Replay-safe tools (e.g. read-only queries) skip the intent write
//! entirely. Side-effecting and resumable tools must persist intent
//! before the executor callback runs.
//!
//! # Execution-intent record
//!
//! [`ExecutionIntent`] is the durable record written before execution.
//! It captures the operation identity, effect class, tool metadata, and
//! timing. The record transitions through:
//!
//! ```text
//!   Pending ──▶ Started ──▶ Completed
//!                  │
//!                  └──▶ Failed
//! ```
//!
//! - **Pending** is written by the guard before the executor fires.
//! - **Started** is set when the executor callback begins (optional
//!   for implementations that can't observe this boundary).
//! - **Completed** / **Failed** are set after the executor returns.
//!
//! # Fail-closed guard
//!
//! [`guarded_tool_execution`] wraps [`super::super::worker::tool_task::execute_tool_task`]
//! with the intent-persistence guard. For side-effecting and resumable
//! tools, if intent persistence fails, the tool callback is **never
//! called** and the child task is failed with a clear error message.
//!
//! # Failure model
//!
//! See the module-level doc of [`failure_model`] for the full decision
//! table that later confirmation and replay work can build on.

use agent_sdk_core::{PendingToolCallInfo, ToolResult};
use anyhow::{Context, bail};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::future::Future;
use std::sync::RwLock;
use time::OffsetDateTime;
use tokio_util::sync::CancellationToken;

use crate::journal::store::AgentTaskStore;
use crate::journal::task::AgentTaskId;
use crate::worker::tool_task::{ToolTaskBootstrap, ToolTaskOutcome, execute_tool_task};

// ─────────────────────────────────────────────────────────────────────
// Operation identity
// ─────────────────────────────────────────────────────────────────────

/// Stable operation identity for a tool execution.
///
/// Combines the server-generated child task id with the LLM-assigned
/// tool call id. This pair is unique across the system, survives
/// retries (the child task id is re-used when the same logical task
/// is re-acquired), and distinguishes independent calls that share
/// an LLM-assigned id.
///
/// # Format
///
/// The string representation is `{child_task_id}:{tool_call_id}`,
/// chosen so it is human-readable in logs and safe for use as a
/// database key.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct OperationId(pub String);

impl OperationId {
    /// Build an operation id from a child task id and tool call id.
    #[must_use]
    pub fn new(child_task_id: &AgentTaskId, tool_call_id: &str) -> Self {
        Self(format!("{}:{}", child_task_id.0, tool_call_id))
    }

    /// The raw string value.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for OperationId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

// ─────────────────────────────────────────────────────────────────────
// Tool effect classification
// ─────────────────────────────────────────────────────────────────────

/// Classification of a tool's side-effect characteristics.
///
/// Drives the durability and retry rules for tool execution.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ToolEffectClass {
    /// The tool is read-only or deterministic and can be replayed
    /// freely. No durable intent is required.
    ///
    /// Examples: balance queries, search, calculations.
    ReplaySafe,

    /// The tool causes external state changes that cannot be undone.
    /// Durable intent **must** be persisted before execution starts.
    /// Automatic retry after a crash is **not safe** unless the intent
    /// record shows the execution never started.
    ///
    /// Examples: transfers, sends, deletes.
    SideEffecting,

    /// The tool starts a long-running operation that can be polled or
    /// resumed. Durable intent **must** be persisted before execution
    /// starts. On retry, the operation id can be used to check status
    /// rather than re-executing.
    ///
    /// Examples: async approval flows, batch jobs.
    Resumable,
}

impl ToolEffectClass {
    /// Whether this class requires durable intent before execution.
    #[must_use]
    pub const fn requires_intent(&self) -> bool {
        matches!(self, Self::SideEffecting | Self::Resumable)
    }

    /// Whether a stale in-flight record for this class is safe to
    /// automatically retry.
    ///
    /// Only replay-safe tools may be retried without further checks.
    /// Side-effecting tools must fail-closed (the operation may have
    /// started). Resumable tools should attempt to resume rather than
    /// re-execute.
    #[must_use]
    pub const fn safe_to_retry(&self) -> bool {
        matches!(self, Self::ReplaySafe)
    }
}

// ─────────────────────────────────────────────────────────────────────
// Execution-intent record
// ─────────────────────────────────────────────────────────────────────

/// Status of a durable execution intent.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum IntentStatus {
    /// Intent persisted; execution has not begun.
    Pending,
    /// Executor callback has been invoked.
    Started,
    /// Executor completed successfully.
    Completed,
    /// Executor returned an error or the guard blocked execution.
    Failed,
}

/// Durable record of intent to execute a tool.
///
/// Written to the [`ExecutionIntentStore`] **before** the tool callback
/// runs. Updated to a terminal status (`Completed` / `Failed`) after
/// the callback returns.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ExecutionIntent {
    /// Stable server-generated operation identity.
    pub operation_id: OperationId,
    /// Side-effect classification that drove the guard decision.
    pub effect_class: ToolEffectClass,
    /// Raw LLM-assigned tool call id (for cross-referencing).
    pub tool_call_id: String,
    /// Child task id that owns this execution.
    pub child_task_id: AgentTaskId,
    /// Tool name.
    pub tool_name: String,
    /// Tool input snapshot (for audit and replay verification).
    pub input: serde_json::Value,
    /// Current status of the intent.
    pub status: IntentStatus,
    /// Error message, populated when `status == Failed`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// When the intent was first persisted.
    #[serde(with = "time::serde::rfc3339")]
    pub created_at: OffsetDateTime,
    /// When the intent last changed status.
    #[serde(with = "time::serde::rfc3339")]
    pub updated_at: OffsetDateTime,
}

impl ExecutionIntent {
    /// Create a new intent in the `Pending` state.
    #[must_use]
    pub fn new(
        operation_id: OperationId,
        effect_class: ToolEffectClass,
        tool_call: &PendingToolCallInfo,
        child_task_id: AgentTaskId,
        now: OffsetDateTime,
    ) -> Self {
        Self {
            operation_id,
            effect_class,
            tool_call_id: tool_call.id.clone(),
            child_task_id,
            tool_name: tool_call.name.clone(),
            input: tool_call.input.clone(),
            status: IntentStatus::Pending,
            error: None,
            created_at: now,
            updated_at: now,
        }
    }

    /// Transition to `Started`.
    pub fn mark_started(&mut self, now: OffsetDateTime) {
        self.status = IntentStatus::Started;
        self.updated_at = now;
    }

    /// Transition to `Completed`.
    pub fn mark_completed(&mut self, now: OffsetDateTime) {
        self.status = IntentStatus::Completed;
        self.updated_at = now;
    }

    /// Transition to `Failed` with an error message.
    pub fn mark_failed(&mut self, error: impl Into<String>, now: OffsetDateTime) {
        self.status = IntentStatus::Failed;
        self.error = Some(error.into());
        self.updated_at = now;
    }

    /// Whether the intent is in a terminal state.
    #[must_use]
    pub const fn is_terminal(&self) -> bool {
        matches!(self.status, IntentStatus::Completed | IntentStatus::Failed)
    }
}

// ─────────────────────────────────────────────────────────────────────
// Store trait
// ─────────────────────────────────────────────────────────────────────

/// Durable store for execution-intent records.
///
/// Every side-effecting or resumable tool must persist an intent
/// through this trait before the executor callback runs. The
/// fail-closed guard in [`guarded_tool_execution`] calls
/// [`persist_intent`](Self::persist_intent) and blocks execution if
/// it fails.
#[async_trait]
pub trait ExecutionIntentStore: Send + Sync {
    /// Persist a new intent record. Must be atomic and durable
    /// (i.e. a crash after this returns `Ok(())` must not lose the
    /// record).
    ///
    /// # Errors
    ///
    /// Returns an error if the record cannot be durably written.
    async fn persist_intent(&self, intent: &ExecutionIntent) -> anyhow::Result<()>;

    /// Update an existing intent record (status transitions).
    ///
    /// # Errors
    ///
    /// Returns an error if the record cannot be updated.
    async fn update_intent(&self, intent: &ExecutionIntent) -> anyhow::Result<()>;

    /// Look up an intent by its [`OperationId`].
    ///
    /// # Errors
    ///
    /// Returns an error if the store cannot be read.
    async fn get_intent(&self, operation_id: &OperationId) -> anyhow::Result<Option<ExecutionIntent>>;

    /// Look up an intent by the child task id.
    ///
    /// # Errors
    ///
    /// Returns an error if the store cannot be read.
    async fn get_intent_by_task(&self, child_task_id: &AgentTaskId) -> anyhow::Result<Option<ExecutionIntent>>;
}

// ─────────────────────────────────────────────────────────────────────
// In-memory store
// ─────────────────────────────────────────────────────────────────────

/// In-memory implementation of [`ExecutionIntentStore`].
///
/// Suitable for testing and single-process deployments.
#[derive(Default)]
pub struct InMemoryExecutionIntentStore {
    intents: RwLock<HashMap<String, ExecutionIntent>>,
    task_index: RwLock<HashMap<String, String>>,
}

impl InMemoryExecutionIntentStore {
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }
}

#[async_trait]
impl ExecutionIntentStore for InMemoryExecutionIntentStore {
    async fn persist_intent(&self, intent: &ExecutionIntent) -> anyhow::Result<()> {
        let op_id = intent.operation_id.as_str().to_owned();
        let task_id = intent.child_task_id.0.clone();
        self.intents
            .write()
            .map_err(|_| anyhow::anyhow!("lock poisoned"))?
            .insert(op_id.clone(), intent.clone());
        self.task_index
            .write()
            .map_err(|_| anyhow::anyhow!("lock poisoned"))?
            .insert(task_id, op_id);
        Ok(())
    }

    async fn update_intent(&self, intent: &ExecutionIntent) -> anyhow::Result<()> {
        self.intents
            .write()
            .map_err(|_| anyhow::anyhow!("lock poisoned"))?
            .insert(intent.operation_id.as_str().to_owned(), intent.clone());
        Ok(())
    }

    async fn get_intent(&self, operation_id: &OperationId) -> anyhow::Result<Option<ExecutionIntent>> {
        Ok(self
            .intents
            .read()
            .map_err(|_| anyhow::anyhow!("lock poisoned"))?
            .get(operation_id.as_str())
            .cloned())
    }

    async fn get_intent_by_task(&self, child_task_id: &AgentTaskId) -> anyhow::Result<Option<ExecutionIntent>> {
        let op_id = self
            .task_index
            .read()
            .map_err(|_| anyhow::anyhow!("lock poisoned"))?
            .get(&child_task_id.0)
            .cloned();
        let Some(op_id) = op_id else {
            return Ok(None);
        };
        Ok(self
            .intents
            .read()
            .map_err(|_| anyhow::anyhow!("lock poisoned"))?
            .get(&op_id)
            .cloned())
    }
}

// ─────────────────────────────────────────────────────────────────────
// Effect classification helper
// ─────────────────────────────────────────────────────────────────────

/// Classify a tool call's effect characteristics.
///
/// The current classification uses the tool's tier from the
/// [`PendingToolCallInfo`] as a heuristic:
///
/// - `Observe` tier → [`ToolEffectClass::ReplaySafe`]
/// - `Confirm` tier → [`ToolEffectClass::SideEffecting`]
/// - `Confirm` tier with `listen_context` → [`ToolEffectClass::Resumable`]
///
/// Future phases may introduce explicit per-tool annotations.
#[must_use]
pub fn classify_tool_effect(tool_call: &PendingToolCallInfo) -> ToolEffectClass {
    use agent_sdk_core::ToolTier;

    match tool_call.tier {
        ToolTier::Observe => ToolEffectClass::ReplaySafe,
        ToolTier::Confirm => {
            if tool_call.listen_context.is_some() {
                ToolEffectClass::Resumable
            } else {
                ToolEffectClass::SideEffecting
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────
// Retry-safety check
// ─────────────────────────────────────────────────────────────────────

/// Result of checking an existing intent for retry safety.
#[derive(Debug)]
pub enum RetryDecision {
    /// No previous intent exists — proceed normally.
    NoPriorIntent,
    /// Previous execution completed — return the cached result.
    AlreadyCompleted(ExecutionIntent),
    /// Previous execution failed before starting — safe to retry.
    FailedBeforeStart(ExecutionIntent),
    /// Previous execution started but didn't complete — unsafe to
    /// retry automatically for side-effecting tools.
    AmbiguousInFlight(ExecutionIntent),
}

/// Check an existing intent record and decide whether retry is safe.
///
/// This is the decision function that later confirmation and replay
/// work will extend.
#[must_use]
pub fn check_retry_safety(prior: Option<ExecutionIntent>) -> RetryDecision {
    let Some(intent) = prior else {
        return RetryDecision::NoPriorIntent;
    };

    match intent.status {
        IntentStatus::Completed => RetryDecision::AlreadyCompleted(intent),
        IntentStatus::Failed => {
            // Failed before execution started (Pending → Failed means
            // the guard blocked it). Safe to retry.
            RetryDecision::FailedBeforeStart(intent)
        }
        IntentStatus::Pending | IntentStatus::Started => {
            if intent.effect_class.safe_to_retry() {
                // Replay-safe: treat as no prior intent.
                RetryDecision::NoPriorIntent
            } else {
                RetryDecision::AmbiguousInFlight(intent)
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────
// Fail-closed guarded execution
// ─────────────────────────────────────────────────────────────────────

/// Execute a tool-runtime child task with durable intent persistence.
///
/// This is the Phase 5.2 wrapper around [`execute_tool_task`] that
/// enforces the fail-closed mutation guard:
///
/// 1. Classify the tool's effect.
/// 2. If the effect requires intent, check for a prior intent
///    (retry-safety).
/// 3. Persist a new intent record.
/// 4. If persistence fails, fail the child task without executing.
/// 5. Delegate to [`execute_tool_task`] with a status-tracking wrapper.
/// 6. Update the intent to terminal status after execution.
///
/// Replay-safe tools bypass the intent write entirely.
pub async fn guarded_tool_execution<F, Fut>(
    bootstrap: ToolTaskBootstrap,
    task_store: &dyn AgentTaskStore,
    intent_store: &dyn ExecutionIntentStore,
    cancel: &CancellationToken,
    effect_class: ToolEffectClass,
    executor: F,
    now: OffsetDateTime,
) -> anyhow::Result<ToolTaskOutcome>
where
    F: FnOnce(PendingToolCallInfo) -> Fut,
    Fut: Future<Output = anyhow::Result<ToolResult>>,
{
    let operation_id = OperationId::new(&bootstrap.task_id, &bootstrap.tool_call.id);

    // ── Replay-safe shortcut ─────────────────────────────────────
    if !effect_class.requires_intent() {
        return execute_tool_task(bootstrap, task_store, cancel, executor, now).await;
    }

    // ── Retry-safety check ───────────────────────────────────────
    let prior = intent_store
        .get_intent(&operation_id)
        .await
        .context("failed to check prior intent")?;

    match check_retry_safety(prior) {
        RetryDecision::AlreadyCompleted(intent) => {
            // Already done. Fail the child task with a note — the
            // result was already committed on the first run. The
            // caller should not have retried.
            bail!(
                "operation {} already completed at {}; refusing duplicate execution",
                intent.operation_id,
                intent.updated_at,
            );
        }
        RetryDecision::AmbiguousInFlight(intent) => {
            // The previous attempt may have started a side-effecting
            // operation. Fail-closed: do not re-execute.
            bail!(
                "operation {} has ambiguous in-flight status ({:?}); \
                 refusing automatic retry for {:?} tool — manual intervention required",
                intent.operation_id,
                intent.status,
                intent.effect_class,
            );
        }
        RetryDecision::NoPriorIntent | RetryDecision::FailedBeforeStart(_) => {
            // Safe to proceed.
        }
    }

    // ── Persist intent (fail-closed) ─────────────────────────────
    let mut intent = ExecutionIntent::new(
        operation_id,
        effect_class,
        &bootstrap.tool_call,
        bootstrap.task_id.clone(),
        now,
    );

    if let Err(persist_err) = intent_store.persist_intent(&intent).await {
        // FAIL-CLOSED: intent could not be durably written.
        // Fail the child task so the parent can handle it.
        let error_msg = format!(
            "fail-closed: could not persist execution intent for tool '{}': {persist_err:#}",
            intent.tool_name,
        );

        let task_id = &bootstrap.task_id;
        let worker_id = &bootstrap.worker_id;
        let lease_id = &bootstrap.lease_id;

        let (child, parent) = task_store
            .fail_task(task_id, worker_id, lease_id, error_msg.clone(), now)
            .await
            .with_context(|| format!("fail_task after intent-persist failure for {task_id}"))?;

        return Ok(ToolTaskOutcome::Failed {
            child,
            parent,
            error: error_msg,
        });
    }

    // ── Mark started ─────────────────────────────────────────────
    intent.mark_started(now);
    // Best-effort: a failure here doesn't block execution since the
    // Pending intent already provides the safety guarantee.
    let _ = intent_store.update_intent(&intent).await;

    // ── Execute ──────────────────────────────────────────────────
    let outcome = execute_tool_task(bootstrap, task_store, cancel, executor, now).await;

    // ── Update intent to terminal status ─────────────────────────
    match &outcome {
        Ok(ToolTaskOutcome::Completed { .. }) => {
            intent.mark_completed(now);
        }
        Ok(ToolTaskOutcome::Failed { error, .. }) => {
            intent.mark_failed(error, now);
        }
        Ok(ToolTaskOutcome::Cancelled) => {
            intent.mark_failed("execution cancelled", now);
        }
        Err(err) => {
            intent.mark_failed(format!("{err:#}"), now);
        }
    }
    // Best-effort: the terminal update is not required for safety —
    // the intent record already prevents unsafe retry.
    let _ = intent_store.update_intent(&intent).await;

    outcome
}

// ─────────────────────────────────────────────────────────────────────
// Failure model documentation
// ─────────────────────────────────────────────────────────────────────

/// # Failure model for durable tool execution
///
/// This module documents every failure mode the execution-intent
/// system handles, organized as a decision table for later
/// confirmation and replay phases to build on.
///
/// ## Failure modes
///
/// | # | Failure point | Effect class | What happens | Recovery |
/// |---|---------------|-------------|--------------|----------|
/// | 1 | Intent persist fails | `SideEffecting` / `Resumable` | **Fail-closed.** Child task is failed without executing. | Retry the child task from scratch. |
/// | 2 | Intent persist fails | `ReplaySafe` | N/A — intent is not required. | Execute directly. |
/// | 3 | Executor crashes after intent `Started` | `SideEffecting` | Intent stays `Started`. On retry, [`check_retry_safety`] returns `AmbiguousInFlight`. **No automatic retry.** | Manual intervention or confirmation from external system. |
/// | 4 | Executor crashes after intent `Started` | `Resumable` | Intent stays `Started`. On retry, [`check_retry_safety`] returns `AmbiguousInFlight`. | Poll the operation id to check if the operation completed. |
/// | 5 | Executor crashes after intent `Started` | `ReplaySafe` | On retry, re-execute freely. | Automatic retry is safe. |
/// | 6 | Intent update to `Completed` fails | Any | Intent stays `Started`, but the task store has the child as `Completed`. | On retry, the task store will reject the retry (already terminal). The intent can be reconciled from the task's terminal state. |
/// | 7 | Task store `complete_task` fails | Any | Intent was `Started`, child is not terminal. | Retry the child task; the intent's `Started` status triggers the appropriate retry decision. |
/// | 8 | Process crashes before intent persist | `SideEffecting` / `Resumable` | No intent exists; no execution happened. | Safe to retry from scratch. |
/// | 9 | Duplicate execution (same operation id) | `SideEffecting` | [`check_retry_safety`] returns `AlreadyCompleted`. | Return error — caller should not have retried. |
///
/// ## Design invariant
///
/// **If a durable intent record does not exist for a side-effecting or
/// resumable tool, the executor callback was never invoked.** This is
/// the core safety guarantee that later phases (confirmation, replay,
/// and manual intervention) can rely on.
///
/// ## Open questions for later phases
///
/// - **User confirmation transport** (out of scope for Phase 5.2):
///   how the `AmbiguousInFlight` decision surfaces to users.
/// - **Automatic resume for `Resumable` tools**: Phase 5.2 treats
///   them the same as `SideEffecting` for retry (fail-closed). Later
///   work should attempt to poll the operation id first.
/// - **Live event replay**: how intent records participate in the
///   event replay contract.
pub mod failure_model {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::journal::task::AgentTaskId;
    use agent_sdk_core::{PendingToolCallInfo, ToolTier};

    // ── OperationId ──────────────────────────────────────────────

    #[test]
    fn operation_id_format() {
        let task_id = AgentTaskId("task_abc123".into());
        let op = OperationId::new(&task_id, "call_xyz");
        assert_eq!(op.as_str(), "task_abc123:call_xyz");
        assert_eq!(op.to_string(), "task_abc123:call_xyz");
    }

    #[test]
    fn operation_id_equality() {
        let a = OperationId::new(&AgentTaskId("t1".into()), "c1");
        let b = OperationId::new(&AgentTaskId("t1".into()), "c1");
        let c = OperationId::new(&AgentTaskId("t2".into()), "c1");
        assert_eq!(a, b);
        assert_ne!(a, c);
    }

    #[test]
    fn operation_id_round_trips_through_json() {
        let op = OperationId::new(&AgentTaskId("task_1".into()), "call_2");
        let json = serde_json::to_string(&op).unwrap();
        let recovered: OperationId = serde_json::from_str(&json).unwrap();
        assert_eq!(op, recovered);
    }

    // ── ToolEffectClass ──────────────────────────────────────────

    #[test]
    fn replay_safe_does_not_require_intent() {
        assert!(!ToolEffectClass::ReplaySafe.requires_intent());
        assert!(ToolEffectClass::ReplaySafe.safe_to_retry());
    }

    #[test]
    fn side_effecting_requires_intent_and_is_not_safe_to_retry() {
        assert!(ToolEffectClass::SideEffecting.requires_intent());
        assert!(!ToolEffectClass::SideEffecting.safe_to_retry());
    }

    #[test]
    fn resumable_requires_intent_and_is_not_safe_to_retry() {
        assert!(ToolEffectClass::Resumable.requires_intent());
        assert!(!ToolEffectClass::Resumable.safe_to_retry());
    }

    // ── classify_tool_effect ─────────────────────────────────────

    fn make_tool_call(tier: ToolTier, listen: bool) -> PendingToolCallInfo {
        PendingToolCallInfo {
            id: "call_1".into(),
            name: "test_tool".into(),
            display_name: "Test Tool".into(),
            tier,
            input: serde_json::json!({}),
            effective_input: serde_json::json!({}),
            listen_context: if listen {
                Some(agent_sdk_core::ListenExecutionContext {
                    operation_id: "op-1".into(),
                    revision: 1,
                    snapshot: serde_json::json!({}),
                    expires_at: None,
                })
            } else {
                None
            },
        }
    }

    #[test]
    fn classify_observe_tool_is_replay_safe() {
        let tool = make_tool_call(ToolTier::Observe, false);
        assert_eq!(classify_tool_effect(&tool), ToolEffectClass::ReplaySafe);
    }

    #[test]
    fn classify_confirm_tool_is_side_effecting() {
        let tool = make_tool_call(ToolTier::Confirm, false);
        assert_eq!(classify_tool_effect(&tool), ToolEffectClass::SideEffecting);
    }

    #[test]
    fn classify_confirm_tool_with_listen_is_resumable() {
        let tool = make_tool_call(ToolTier::Confirm, true);
        assert_eq!(classify_tool_effect(&tool), ToolEffectClass::Resumable);
    }

    // ── ExecutionIntent lifecycle ────────────────────────────────

    #[test]
    fn intent_lifecycle_transitions() {
        let op = OperationId::new(&AgentTaskId("t1".into()), "c1");
        let tool = make_tool_call(ToolTier::Confirm, false);
        let now = OffsetDateTime::now_utc();

        let mut intent = ExecutionIntent::new(
            op,
            ToolEffectClass::SideEffecting,
            &tool,
            AgentTaskId("t1".into()),
            now,
        );
        assert_eq!(intent.status, IntentStatus::Pending);
        assert!(!intent.is_terminal());

        intent.mark_started(now);
        assert_eq!(intent.status, IntentStatus::Started);
        assert!(!intent.is_terminal());

        intent.mark_completed(now);
        assert_eq!(intent.status, IntentStatus::Completed);
        assert!(intent.is_terminal());
    }

    #[test]
    fn intent_failed_is_terminal() {
        let op = OperationId::new(&AgentTaskId("t1".into()), "c1");
        let tool = make_tool_call(ToolTier::Confirm, false);
        let now = OffsetDateTime::now_utc();

        let mut intent = ExecutionIntent::new(
            op,
            ToolEffectClass::SideEffecting,
            &tool,
            AgentTaskId("t1".into()),
            now,
        );
        intent.mark_failed("something broke", now);
        assert_eq!(intent.status, IntentStatus::Failed);
        assert!(intent.is_terminal());
        assert_eq!(intent.error.as_deref(), Some("something broke"));
    }

    #[test]
    fn intent_round_trips_through_json() {
        let op = OperationId::new(&AgentTaskId("t1".into()), "c1");
        let tool = make_tool_call(ToolTier::Confirm, false);
        let now = OffsetDateTime::now_utc();

        let intent = ExecutionIntent::new(
            op,
            ToolEffectClass::SideEffecting,
            &tool,
            AgentTaskId("t1".into()),
            now,
        );
        let json = serde_json::to_string(&intent).unwrap();
        let recovered: ExecutionIntent = serde_json::from_str(&json).unwrap();
        assert_eq!(recovered.operation_id, intent.operation_id);
        assert_eq!(recovered.effect_class, intent.effect_class);
        assert_eq!(recovered.status, intent.status);
        assert_eq!(recovered.tool_name, intent.tool_name);
    }

    // ── RetryDecision ────────────────────────────────────────────

    #[test]
    fn no_prior_intent_returns_no_prior() {
        assert!(matches!(
            check_retry_safety(None),
            RetryDecision::NoPriorIntent
        ));
    }

    #[test]
    fn completed_intent_returns_already_completed() {
        let op = OperationId::new(&AgentTaskId("t1".into()), "c1");
        let tool = make_tool_call(ToolTier::Confirm, false);
        let now = OffsetDateTime::now_utc();
        let mut intent = ExecutionIntent::new(
            op,
            ToolEffectClass::SideEffecting,
            &tool,
            AgentTaskId("t1".into()),
            now,
        );
        intent.mark_completed(now);
        assert!(matches!(
            check_retry_safety(Some(intent)),
            RetryDecision::AlreadyCompleted(_)
        ));
    }

    #[test]
    fn failed_intent_returns_failed_before_start() {
        let op = OperationId::new(&AgentTaskId("t1".into()), "c1");
        let tool = make_tool_call(ToolTier::Confirm, false);
        let now = OffsetDateTime::now_utc();
        let mut intent = ExecutionIntent::new(
            op,
            ToolEffectClass::SideEffecting,
            &tool,
            AgentTaskId("t1".into()),
            now,
        );
        intent.mark_failed("blocked", now);
        assert!(matches!(
            check_retry_safety(Some(intent)),
            RetryDecision::FailedBeforeStart(_)
        ));
    }

    #[test]
    fn started_side_effecting_returns_ambiguous() {
        let op = OperationId::new(&AgentTaskId("t1".into()), "c1");
        let tool = make_tool_call(ToolTier::Confirm, false);
        let now = OffsetDateTime::now_utc();
        let mut intent = ExecutionIntent::new(
            op,
            ToolEffectClass::SideEffecting,
            &tool,
            AgentTaskId("t1".into()),
            now,
        );
        intent.mark_started(now);
        assert!(matches!(
            check_retry_safety(Some(intent)),
            RetryDecision::AmbiguousInFlight(_)
        ));
    }

    #[test]
    fn pending_replay_safe_returns_no_prior() {
        let op = OperationId::new(&AgentTaskId("t1".into()), "c1");
        let tool = make_tool_call(ToolTier::Observe, false);
        let now = OffsetDateTime::now_utc();
        let intent = ExecutionIntent::new(
            op,
            ToolEffectClass::ReplaySafe,
            &tool,
            AgentTaskId("t1".into()),
            now,
        );
        assert!(matches!(
            check_retry_safety(Some(intent)),
            RetryDecision::NoPriorIntent
        ));
    }

    // ── InMemoryExecutionIntentStore ─────────────────────────────

    #[tokio::test]
    async fn in_memory_store_persist_and_get() {
        let store = InMemoryExecutionIntentStore::new();
        let op = OperationId::new(&AgentTaskId("t1".into()), "c1");
        let tool = make_tool_call(ToolTier::Confirm, false);
        let now = OffsetDateTime::now_utc();

        let intent = ExecutionIntent::new(
            op.clone(),
            ToolEffectClass::SideEffecting,
            &tool,
            AgentTaskId("t1".into()),
            now,
        );

        store.persist_intent(&intent).await.unwrap();

        let loaded = store.get_intent(&op).await.unwrap();
        assert!(loaded.is_some());
        let loaded = loaded.unwrap();
        assert_eq!(loaded.operation_id, op);
        assert_eq!(loaded.status, IntentStatus::Pending);
    }

    #[tokio::test]
    async fn in_memory_store_get_by_task() {
        let store = InMemoryExecutionIntentStore::new();
        let task_id = AgentTaskId("task_42".into());
        let op = OperationId::new(&task_id, "c1");
        let tool = make_tool_call(ToolTier::Confirm, false);
        let now = OffsetDateTime::now_utc();

        let intent = ExecutionIntent::new(
            op,
            ToolEffectClass::SideEffecting,
            &tool,
            task_id.clone(),
            now,
        );

        store.persist_intent(&intent).await.unwrap();

        let loaded = store.get_intent_by_task(&task_id).await.unwrap();
        assert!(loaded.is_some());
        assert_eq!(loaded.unwrap().child_task_id, task_id);
    }

    #[tokio::test]
    async fn in_memory_store_update_transitions_status() {
        let store = InMemoryExecutionIntentStore::new();
        let op = OperationId::new(&AgentTaskId("t1".into()), "c1");
        let tool = make_tool_call(ToolTier::Confirm, false);
        let now = OffsetDateTime::now_utc();

        let mut intent = ExecutionIntent::new(
            op.clone(),
            ToolEffectClass::SideEffecting,
            &tool,
            AgentTaskId("t1".into()),
            now,
        );

        store.persist_intent(&intent).await.unwrap();

        intent.mark_started(now);
        store.update_intent(&intent).await.unwrap();

        let loaded = store.get_intent(&op).await.unwrap().unwrap();
        assert_eq!(loaded.status, IntentStatus::Started);

        intent.mark_completed(now);
        store.update_intent(&intent).await.unwrap();

        let loaded = store.get_intent(&op).await.unwrap().unwrap();
        assert_eq!(loaded.status, IntentStatus::Completed);
    }

    #[tokio::test]
    async fn in_memory_store_get_nonexistent_returns_none() {
        let store = InMemoryExecutionIntentStore::new();
        let op = OperationId("nonexistent:call".into());
        assert!(store.get_intent(&op).await.unwrap().is_none());
        assert!(store
            .get_intent_by_task(&AgentTaskId("nope".into()))
            .await
            .unwrap()
            .is_none());
    }
}
